mutation initAttendance($schedule: ScheduleInput! $attendance: String!) {
  attendance: initAttendance(schedule: $schedule attendance: $attendance) {
    secret
    students {
      id
      name
      attendance
      absentReason
    }
  }
}
