mutation markAttendance($schedule: ScheduleInput! $student: String! $attendance: String!) {
  markAttendance(schedule: $schedule student: $student attendance: $attendance) {
    id
    attendance
    # Schedule
    classcode
    date
    startTime
    endTime
    classType
  }
}
