mutation updateAttendance($otp: String!) {
  updateAttendance(otp: $otp)
  @NgModule(module: "src/app/graphql.module#GraphQLModule") {
    id
    attendance
    # Schedule
    classcode
    date
    startTime
    endTime
    classType
  }
}
