query attendance($schedule: ScheduleInput!) {
  attendance(schedule: $schedule)
  @NgModule(module: "src/app/graphql.module#GraphQLModule") {
    secret
    students {
      id
      name
      attendance
      absentReason
    }
    log {
      lectureUpdate
      otherInfo
      nextLecturePlan
    }
  }
}
