mutation markAttendance(
  $schedule: ScheduleInput!
  $student: String!
  $attendance: String!
  $absentReason: String
) {
  markAttendance(
    schedule: $schedule
    student: $student
    attendance: $attendance
    absentReason: $absentReason
  ) @NgModule(module: "src/app/graphql.module#GraphQLModule") {
    id
    attendance
    absentReason
    # Schedule
    classcode
    date
    startTime
    endTime
    classType
  }
}
