subscription NewStatus(
  $classcode: String!
  $date: String!
  $startTime: String!
  $endTime: String!
  $classType: String!
) {
  newStatus(
    classcode: $classcode
    date: $date
    startTime: $startTime
    endTime: $endTime
    classType: $classType
  ) @NgModule(module: "src/app/graphql.module#GraphQLModule") {
    id
    attendance
    absentReason
  }
}
