export { StaffProfile } from './staff-profile';
export { Apcard } from './apcard';
export { Attendance } from './attendance';
export { BusTrips, Trips } from './bus-trips';
export { Course } from './courses';
export { CourseDetails } from './course-details';
export { ExamSchedule } from './exam-schedule';
export { FeesBankDraft, FeesDetails, FeesSummary, FeesTotalSummary } from './fees';
export { LecturerTimetable } from './lecturer-timetable';
export { News } from './news';
export { OperationHours } from './operation-hours';
export { Role, Settings } from './settings';
export { Sqa } from './sqa';
export { StaffDirectory } from './staff-directory';
export { StudentPhoto } from './student-photo';
export { StudentProfile } from './student-profile';
export { Subcourse } from './subcourses';
export { Timetable } from './timetable';
export { AttendanceLegend } from './attendance-legend';
export { InterimLegend } from './interim-legend';
export { MPULegend } from './mpu-legend';
export { DeterminationLegend } from './determination-legend';
export { ClassificationLegend } from './classfication-legend';
export { Notification } from './notification';
