export { AcademicProfile } from './academic-profile';
export { Apcard } from './apcard';
export { Attendance } from './attendance';
export { BusTrips, Trips } from './bus-trips';
export { Course } from './courses';
export { CourseDetails } from './course-details';
export { FeesBankDraft, FeesDetails, FeesSummary, FeesTotalSummary } from './fees';
export { News } from './news';
export { OperationHours } from './operation-hours';
export { Sqa } from './sqa';
export { StaffDirectory } from './staff-directory';
export { StudentPhoto } from './student-photo';
export { StudentProfile } from './student-profile';
export { Subcourse } from './subcourses';
export { Timetable } from './timetable';
